//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : bangbangla
//  @ File Name : ServerResult.java
//  @ Date : 2022/7/6
//  @ Author : 
//
//



package com.sallee.bangbangla.pojo;


public class ServerResult {
	Integer state;
	String mag;
	Object data;

	public ServerResult(Integer state, String mag, Object data) {
		this.state = state;
		this.mag = mag;
		this.data = data;
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getMag() {
		return mag;
	}

	public void setMag(String mag) {
		this.mag = mag;
	}

	public Object getData() {
		return data;
	}

	public void setData(Object data) {
		this.data = data;
	}
}
